# Generated by Django 4.1.13 on 2024-07-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='environmental_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateField()),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('power', models.FloatField()),
                ('voltage', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='sample_data',
        ),
    ]
