# Generated by Django 4.1.13 on 2024-07-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_environmental_data_delete_sample_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentalData',
            fields=[
                ('datetime', models.DateTimeField(primary_key=True, serialize=False)),
                ('temperature', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('current', models.IntegerField()),
                ('voltage', models.IntegerField()),
                ('luminosity', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='environmental_data',
        ),
    ]
