# Generated by Django 4.1.13 on 2024-07-30 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_environmentaldata_delete_environmental_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmentaldata',
            name='datetime',
            field=models.DateField(primary_key=True, serialize=False),
        ),
    ]
