# Generated by Django 4.1.13 on 2024-07-30 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_environmentaldata_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='environmentaldata',
            old_name='datetime',
            new_name='day',
        ),
    ]
